/**
 * Generate the out-of-band `aws scheduler create-schedule` commands for every
 * ingestion job, straight from the canonical INGESTION_JOBS matrix — so the
 * out-of-band schedules can never drift from the (future) CDK ones.
 *
 *   cd infra/cdk
 *   npx tsx scripts/gen-ingestion-schedules.ts > /tmp/create-ingestion-schedules.sh
 *   # review, then run with the env vars set (see header it emits):
 *   bash /tmp/create-ingestion-schedules.sh
 *
 * The emitted script reads these env vars (no account-specifics hardcoded):
 *   CLUSTER_ARN, TD_ARN, SCHED_ROLE_ARN, SUBNETS (JSON array), SG (JSON array),
 *   ENV (default 'dev'), CONTAINER (default 'api'), DRY_RUN (default '0').
 *
 * AWS EventBridge Scheduler cron is 6-field: cron(min hr day-of-month month day-of-week year).
 * Exactly one of day-of-month / day-of-week must be '?'. We mirror the CDK
 * construct's field resolution so both produce identical schedules.
 */
import { INGESTION_JOBS, type ScheduledIngestionJob } from '../lib/ingestion-schedule';

/** kebab a PascalCase id: SyncCongress -> sync-congress (matches CDK rule names). */
function kebab(id: string): string {
  return id.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

/** Build the 6-field AWS Scheduler cron from the job's cron fields. */
function awsCron(job: ScheduledIngestionJob): string {
  const c = job.cron;
  const minute = c.minute;
  const hour = c.hour;
  const month = c.month ?? '*';
  const weekDay = c.weekDay;
  // Mirror the CDK construct: if weekDay is set, day-of-month is '?'; else day
  // defaults to '*' (and day-of-week becomes '?'). AWS requires exactly one '?'.
  let dom: string;
  let dow: string;
  if (weekDay) {
    dom = c.day ?? '?';
    dow = weekDay;
  } else {
    dom = c.day ?? '*';
    dow = '?';
  }
  // If both ended up concrete (shouldn't with our matrix), force dow='?'.
  if (dom !== '?' && dow !== '?') dow = '?';
  return `cron(${minute} ${hour} ${dom} ${month} ${dow} *)`;
}

/** Shell-quote a JSON string for embedding in single-quoted bash. */
function sh(s: string): string {
  return s.replace(/'/g, `'\\''`);
}

function emit(): string {
  const lines: string[] = [];
  lines.push('#!/usr/bin/env bash');
  lines.push('# AUTO-GENERATED by infra/cdk/scripts/gen-ingestion-schedules.ts');
  lines.push('# Source of truth: infra/cdk/lib/ingestion-schedule.ts. Do not hand-edit.');
  lines.push('set -euo pipefail');
  lines.push('');
  lines.push(': "${CLUSTER_ARN:?set CLUSTER_ARN}"');
  lines.push(': "${TD_ARN:?set TD_ARN (e.g. ...:task-definition/capiro-dev-api-sync:1)}"');
  lines.push(': "${SCHED_ROLE_ARN:?set SCHED_ROLE_ARN (capiro-dev-ingestion-scheduler)}"');
  lines.push(': "${SUBNETS:?set SUBNETS as JSON array e.g. [\\"subnet-a\\",\\"subnet-b\\"]}"');
  lines.push(': "${SG:?set SG as JSON array e.g. [\\"sg-xxx\\"]}"');
  lines.push('ENV="${ENV:-dev}"');
  lines.push('CONTAINER="${CONTAINER:-api}"');
  lines.push('DRY_RUN="${DRY_RUN:-0}"');
  lines.push('');
  lines.push('create_sched () {  # $1=name-suffix  $2=cron  $3=command-json-array  $4=description');
  lines.push('  local name="capiro-${ENV}-$1"');
  lines.push('  local input="{\\"containerOverrides\\":[{\\"name\\":\\"${CONTAINER}\\",\\"command\\":$3}]}"');
  lines.push('  local target="{');
  lines.push('    \\"Arn\\":\\"${CLUSTER_ARN}\\",');
  lines.push('    \\"RoleArn\\":\\"${SCHED_ROLE_ARN}\\",');
  lines.push('    \\"EcsParameters\\":{\\"TaskDefinitionArn\\":\\"${TD_ARN}\\",\\"LaunchType\\":\\"FARGATE\\",');
  lines.push('      \\"NetworkConfiguration\\":{\\"awsvpcConfiguration\\":{\\"Subnets\\":${SUBNETS},\\"SecurityGroups\\":${SG},\\"AssignPublicIp\\":\\"DISABLED\\"}}},');
  lines.push('    \\"Input\\":\\"$(printf %s "$input" | sed "s/\\"/\\\\\\\\\\"/g")\\"');
  lines.push('  }"');
  lines.push('  if [ "$DRY_RUN" = "1" ]; then');
  lines.push('    echo "[dry-run] $name  $2  $3"');
  lines.push('    return 0');
  lines.push('  fi');
  lines.push('  MSYS_NO_PATHCONV=1 aws scheduler create-schedule \\');
  lines.push('    --name "$name" \\');
  lines.push('    --schedule-expression "$2" \\');
  lines.push('    --schedule-expression-timezone "UTC" \\');
  lines.push('    --flexible-time-window \x27{"Mode":"OFF"}\x27 \\');
  lines.push('    --description "$4" \\');
  lines.push('    --target "$target"');
  lines.push('  echo "created $name"');
  lines.push('}');
  lines.push('');

  let lastTier = '';
  for (const job of INGESTION_JOBS) {
    if (job.tier !== lastTier) {
      lines.push(`# ── ${job.tier.toUpperCase()} ───────────────────────────────`);
      lastTier = job.tier;
    }
    const name = kebab(job.id);
    const cron = awsCron(job);
    const cmdJson = JSON.stringify(job.command); // ["sync-congress"]
    lines.push(`create_sched ${name} '${cron}' '${cmdJson}' '${sh(job.description)}'`);
  }
  lines.push('');
  lines.push(`echo "Done: ${INGESTION_JOBS.length} ingestion schedules processed (DRY_RUN=$DRY_RUN)."`);
  lines.push('# NOTE: embed-backfill --source all (13:00 UTC) is created separately; see the runbook.');
  lines.push('');
  return lines.join('\n');
}

process.stdout.write(emit());
