-- Review queue for proposed person -> Program Element links. Generated by the
-- PE-person matcher (deterministic org/title token overlap vs PE + project titles).
-- Candidates are NEVER auto-applied: a reviewer confirms one, which then sets
-- acquisition_personnel.pe_primary. Mirrors acquisition_personnel_merge_candidate.

CREATE TABLE IF NOT EXISTS "program_element_person_candidate" (
    "id"                 UUID         NOT NULL DEFAULT gen_random_uuid(),
    "person_id"          UUID         NOT NULL,
    "pe_code"            VARCHAR(16)  NOT NULL,
    "score"              DOUBLE PRECISION NOT NULL,
    "match_basis"        TEXT,
    "score_breakdown_jsonb" JSONB     NOT NULL DEFAULT '{}',
    "status"             VARCHAR(20)  NOT NULL DEFAULT 'open',
    "resolved_by_user_id" UUID,
    "resolved_at"        TIMESTAMPTZ(6),
    "decision_notes"     TEXT,
    "created_at"         TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
    CONSTRAINT "program_element_person_candidate_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "program_element_person_candidate_person_pe_key"
    ON "program_element_person_candidate" ("person_id", "pe_code");

CREATE INDEX IF NOT EXISTS "program_element_person_candidate_status_idx"
    ON "program_element_person_candidate" ("status");

CREATE INDEX IF NOT EXISTS "program_element_person_candidate_pe_code_idx"
    ON "program_element_person_candidate" ("pe_code");
